site_name: Hikari of ME                                       # 站点名称
site_url: https://mydomain.org/hikari-of-me/                  # 站点 URL
repo_url: https://git.zju.edu.cn/hikari-of-me/hikari-of-me    # 仓库 URL
repo_name: Repository of hikari-of-me                         # 仓库名称（显示在右上角的）

theme:
  name: material                                              # 主题名称为 material          

  palette:

    # 浅色模式的主题色为紫色
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: purple

    # 深色模式的主题色为默认
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Noto Serif SC               # 正文字体为 Noto Serif SC，其中 SC = Simplified Chinese

  language: zh                        # 站点语言为简体中文

  features:
    - navigation.instant              # 启用即时导航功能，使页面切换更快
    - navigation.instant.prefetch     # 启用预取功能，在用户点击链接前预加载页面内容
    - navigation.instant.progress     # 启用加载进度条，显示页面加载状态（低于 400 ms 则不显示）
    - navigation.tabs                 # 启用标签式导航，使页面内容以标签页的形式展示
    - navigation.tabs.sticky          # 启用粘性标签，使标签页在滚动时保持可见（把导航栏固定住，不会随用户下滑而隐藏）
    - navigation.sections             # 启用章节导航，在页面侧边显示当前章节的目录结构  
    - navigation.path                 # 启用路径导航，在页面顶部显示当前页面的路径结构（存疑）
    - navigation.top                  # 启用返回顶部按钮，点击后滚动回页面顶部
    - search.suggest                  # 启用搜索建议，在搜索框输入时显示相关页面的建议列表
    - search.highlight                # 启用搜索高亮，在搜索结果页面高亮显示匹配的关键词
    - search.share                    # 启用搜索分享，在搜索结果页面显示分享按钮，允许用户分享搜索结果链接（存疑）

plugins:
  - search                            # 启用搜索插件，提供站内搜索功能
  - git-revision-date-localized:
      enable_creation_date: false     # 启用 Git 修订日期插件，显示页面的最后修改日期（不显示创建日期）

markdown_extensions:                  # Markdown 的扩展内容，这里直接复制了 Material for MkDocs 官方文档的推荐配置

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 主页: index.md
  - 信息查询: information.md
  - 升学之路: leap.md
  - 机缘于此: 
    - 幕启: meStory/index.md
    - 项目式学习：推荐大家在大学的时候补上的一课: meStory/chapter1.md
    - 机械碎碎念（一）：机械是什么: meStory/chapter2.md
    - 机械碎碎念（二）：学了机械以后做什么: meStory/chapter3.md
    - 机械碎碎念（三）：机械，一个传统的行业: meStory/chapter4.md
    - 一个老登的工作感悟——2025年增补版: meStory/chapter5.md
  - 课程导航: 
    - 23级培养方案: nav23.md
    - 24级培养方案: nav24.md
  - 专业基础课:
    - 工程材料: courses/basic/gc/index.md
    - 理论力学（甲）: courses/basic/lily/index.md
    - 电工电子学: courses/basic/dg/index.md
    - 电工电子学实验: courses/basic/dgsy/index.md
    - 材料力学（乙）: courses/basic/cl/index.md
    - 材料力学实验: courses/basic/clsy/index.md
  - 专业必修课:
    - 设计与制造Ⅰ: courses/compulsory/sz1/index.md
    - 设计与制造Ⅱ: courses/compulsory/sz2/index.md
    - 互换性与技术测量: courses/compulsory/hhx/index.md
    - 工程流体力学 & 热工基础: courses/compulsory/glrg/index.md
    - 设计与制造Ⅲ: courses/compulsory/sz3/index.md
    - 机械工程测试技术: courses/compulsory/cs/index.md
    - 控制工程基础: courses/compulsory/kz/index.md
    - 液压传动及控制Ⅰ: courses/compulsory/yy1/index.md
    - 仅23级:
      - 机械系统动力学: courses/compulsory/jxxt/index.md
      - 嵌入式系统: courses/compulsory/qrs/index.md
  - 专业选修课:
    - 一、机电技术类（仅23级）:
      - 有限元分析: courses/optional/yxy/index.md
      - 机械优化设计: courses/optional/yh/index.md
      - 机电系统设计与仿真: courses/optional/jdxt/index.md
      - 智能制造系统: courses/optional/zzxt/index.md
      - 机械结构强度学: courses/optional/jg/index.md
      - 机器人技术: courses/optional/defect/index.md
      - 微纳制造技术基础: courses/optional/nano/index.md
    - 二、信息技术类（仅23级）:
      - 人工智能及其工程应用: courses/optional/ai/index.md
      - 工业大数据技术与应用: courses/optional/dsj/index.md
      - 工业软件开发技术: courses/optional/shit/index.md
      - 制造物联网技术导论: courses/optional/wlw/index.md
  - 专业模块课: 
    - 23级模块课一览: courses/module/index.md
    - 一、设计制造模块:
      - 计算机辅助设计与制造: courses/module/cadcam/index.md
      - 产品设计方法: courses/module/cp/index.md
      - 机械制造技术: courses/module/jxzz/index.md
      - 数控技术及其装备: courses/module/sk/index.md
    - 二、机电控制模块:
      - 电机控制与拖动: courses/module/dj/index.md
      - 线性系统与数字控制: courses/module/xxxt/index.md
      - 液压传动及控制Ⅱ: courses/module/yy2/index.md
      - 机电系统建模、辨识与控制: courses/module/shit/index.md
    - 三、制造系统管理模块:
      - 制造系统决策与优化: courses/module/jc/index.md
      - 质量管理与控制: courses/module/zl/index.md
      - 精益生产: courses/module/jy/index.md
      - 制造系统信息化: courses/module/zzxt/index.md
    - 24级模块课暂存: 
      - 机器人技术基础（机器人模块）: courses/module/defect/index.md
  - 实践教学课:
    - 23级（可参考）:
      - 专业前沿认识实习: courses/practice/rssx/index.md
      - 机械原理课程设计: courses/practice/jxyl/index.md
      - 工程拓展训练: courses/practice/gt/index.md
      - 机械工程基础实验 & 测控技术实验: courses/practice/sy/index.md
      - 生产实习: courses/practice/work/index.md
      - 机械设计课程设计（甲）: courses/practice/jxsj/index.md
      - 机电系统综合实验: courses/practice/jdsy/index.md
  - 个性修读课:
    - 工程数值方法: courses/personality/gs/index.md
    - 增材制造: courses/personality/zc/index.md
    - 微机电系统基础: courses/personality/mems/index.md
  - 资源推荐: recommendation.md